# Development - docker compose -f compose.dev.yml up

services:
  db:
    container_name: barae-dev-db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dev-pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 30

  mailpit:
    container_name: barae-dev-mailpit
    image: axllent/mailpit:latest
    restart: unless-stopped
    ports:
      - "8025:8025"
      - "1025:1025"
    environment:
      MP_SMTP_AUTH_ACCEPT_ANY: 1
      MP_SMTP_AUTH_ALLOW_INSECURE: 1

  backend:
    container_name: barae-dev-backend
    build:
      context: .
      dockerfile: Dockerfile.backend
      target: dev
    depends_on:
      db:
        condition: service_healthy
      mailpit:
        condition: service_started
    env_file: .env
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      SMTP_HOST: ${SMTP_HOST:-mailpit}
      SMTP_PORT: ${SMTP_PORT:-1025}
      SMTP_USER: ${SMTP_USER:-}
      SMTP_PASSWORD: ${SMTP_PASSWORD:-}
      SMTP_SECURE: ${SMTP_SECURE:-false}
      EMAIL_FROM: ${EMAIL_FROM:-Barae <noreply@barae.local>}
      AUTH_BASE_URL: ${AUTH_BASE_URL:-http://localhost:8100/api/v1}
    volumes:
      - ./backend:/app
      - /app/node_modules
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://127.0.0.1:3000/health"]
      interval: 10s
      timeout: 3s
      retries: 30
      start_period: 10s

  frontend:
    container_name: barae-dev-frontend
    build:
      context: .
      dockerfile: Dockerfile.proxy
      target: dev-frontend
    volumes:
      - ./frontend:/app
      - /app/node_modules

  proxy:
    container_name: barae-dev-proxy
    build:
      context: .
      dockerfile: Dockerfile.proxy
      target: dev
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_started
    ports:
      - "8100:8100"
    volumes:
      - ./caddy/Caddyfile.dev:/etc/caddy/Caddyfile

volumes:
  dev-pg-data:
