# Development Docker Compose
# Usage: docker compose -f compose.dev.yml up
#
# This configuration:
# - Mounts source code for hot reload
# - Exposes ports directly for debugging
# - Uses separate dev containers

services:
  db:
    container_name: barae-dev-db
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - dev-pg-data:/var/lib/postgresql/data
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 3s
      retries: 30
      start_period: 5s

  backend:
    container_name: barae-dev-backend
    build:
      context: ./backend
      target: dev
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: development
      SERVER_HOST: ${SERVER_HOST:-0.0.0.0}
      SERVER_PORT: ${SERVER_PORT:-3000}
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_SECRET: ${APP_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-}
      FRONTEND_URL: ${FRONTEND_URL:-http://localhost:5173}
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      EMAIL_FROM: ${EMAIL_FROM:-}
    ports:
      - "${SERVER_PORT:-3000}:3000"
    volumes:
      - ./backend:/app
      - /app/node_modules

  frontend:
    container_name: barae-dev-frontend
    build:
      context: ./frontend
      target: dev
    environment:
      VITE_API_URL: ${VITE_API_URL:-http://localhost:3000}
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules

volumes:
  dev-pg-data:
    name: barae-dev-pg-data
