# Production Docker Compose
# Usage: docker compose -f compose.prod.yml up -d
#
# This configuration:
# - Uses production builds
# - Nginx reverse proxy handles routing
# - All services on internal network except nginx
# - Database not exposed to host

services:
  db:
    container_name: barae-db
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    networks:
      - internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    container_name: barae-backend
    build:
      context: ./backend
      target: prod
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      NODE_ENV: production
      SERVER_HOST: 0.0.0.0
      SERVER_PORT: 3000
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      APP_SECRET: ${APP_SECRET}
      GITHUB_CLIENT_ID: ${GITHUB_CLIENT_ID:-}
      GITHUB_CLIENT_SECRET: ${GITHUB_CLIENT_SECRET:-}
      FRONTEND_URL: ${FRONTEND_URL}
      RESEND_API_KEY: ${RESEND_API_KEY:-}
      EMAIL_FROM: ${EMAIL_FROM:-}
    networks:
      - internal
    expose:
      - "3000"

  frontend:
    container_name: barae-frontend-build
    build:
      context: ./frontend
      target: build
      args:
        VITE_API_URL: /api
    # This is a build-only container, outputs to volume
    volumes:
      - frontend-dist:/app/dist

  nginx:
    container_name: barae-nginx
    build:
      context: ./nginx
    restart: always
    depends_on:
      - backend
      - frontend
    ports:
      - "${HTTP_PORT:-80}:80"
    volumes:
      - frontend-dist:/usr/share/nginx/html:ro
    networks:
      - internal
      - external

networks:
  internal:
    driver: bridge
    internal: true
  external:
    driver: bridge

volumes:
  pg-data:
    name: barae-pg-data
  frontend-dist:
    name: barae-frontend-dist
