# Production - docker compose -f compose.prod.yml up -d

services:
  db:
    container_name: barae-db
    image: postgres:17-alpine
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pg-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    container_name: barae-backend
    build:
      context: ./backend
      target: prod
    restart: always
    depends_on:
      db:
        condition: service_healthy
    env_file: .env
    environment:
      NODE_ENV: production
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
    expose:
      - "3000"

  frontend:
    container_name: barae-frontend
    build:
      context: ./frontend
      target: prod
    restart: always
    depends_on:
      - backend
    ports:
      - "${HTTP_PORT:-80}:80"

volumes:
  pg-data:
